#!/bin/sh

# 禁止APC缓存
echo 'php_value apc.cache_by_default off' > ${OPENSHIFT_REPO_DIR}/.htaccess

# 输出环境变量
echo -e '<?php\n$env=<<<Environment' > ${OPENSHIFT_REPO_DIR}/environment_info.php
env >> ${OPENSHIFT_REPO_DIR}/environment_info.php
echo 'Environment;' >> ${OPENSHIFT_REPO_DIR}/environment_info.php